name: Convert to base64

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Convert base64
      run: |
          > list64
          content=$(cat list | base64 | tr -d '\n')
            echo "$content" > list64

    - name: Check for base64 Changes
      id: changes64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'
            
    - name: Push Base64
      if: steps.changes64.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git commit --allow-empty -m "Convert to base64"
          git push

    - name: Convert Channels base64
      run: |
          > gitChannels64
          content=$(cat gitChannels | base64 | tr -d '\n')
            echo "$content" > gitChannels64

    - name: Check for Channels base64 Changes
      id: changesChannels
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'
            
    - name: Push Channels Base64
      if: steps.changesChannels.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git commit --allow-empty -m "Convert to base64"
          git push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip

    - name: Run script to select random lines
      run: |
          python selector/random_lines.py

    - name: Push Random
      if: steps.changesRandom.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selector/random
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push

    - name: Convert Random to base64
      run: |
          > selector/random64
          content=$(cat selector/random | base64 | tr -d '\n')
            echo "$content" > selector/random64

    - name: Check for Channels base64 Changes
      id: changesRandom64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'
            
    - name: Push Channels Base64
      if: steps.changesRandom64.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push
          
    - name: Run script to select random lines channels
      run: |
          python selector/random_lines_ch.py

    - name: Push Random
      if: steps.changesRandom.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add selector/random_ch
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push

    - name: Convert Random to base64
      run: |
          > selector/random_ch64
          content=$(cat selector/random | base64 | tr -d '\n')
            echo "$content" > selector/random_ch64

    - name: Check for Channels base64 Changes
      id: changesChRandom64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'
            
    - name: Push Channels Base64
      if: steps.changesChRandom64.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push


    - name: Run script to rename address
      run: |
          python iprename/iprename.py
          
    - name: Check for Renamed Base64 Changes
      id: changesip
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
    - name: Commit and Push Renamed Base64
      if: steps.changesip.outputs.changed == 'true'   
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add iprename/iprename
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push


    - name: Run script to rename address
      run: |
          python iprename/iprename.py
          
    - name: Check for Renamed Base64 Changes
      id: changesip
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
    - name: Commit and Push Renamed Base64
      if: steps.changesip.outputs.changed == 'true'   
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add iprename/iprename
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push

    - name: Convert IPRename to base64
      run: |
          content=$(cat iprename/iprename | base64 | tr -d '\n')
            echo "$content" > iprename/iprename64
            
    - name: Check for Renamed Base64 Changes
      id: changesip64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
    - name: Commit and Push Renamed Base64
      if: steps.changesip64.outputs.changed == 'true'   
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add iprename/iprename64
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push

